import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav/navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/footer/footer";
import { Toaster } from "@/components/ui/sonner";
import { AnimatePresence } from "framer-motion";
import { Suspense } from "react";
import { Skeleton } from "@/components/ui/skeleton";

const font = Montserrat({
	weight: "400",
	subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Medical Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en" className="overflow-x-hidden">
				<body className={`${font.className} w-screen overflow-x-hidden antialiased`}>
					<header className="mb-32 ">
						<NavBar />
					</header>
					<main className="max-w-7xl mx-auto px-2 min-h-screen flex flex-col">
						<div className="flex-grow">
							{children}
						</div>
						<Footer />
					</main>

					<Toaster
						closeButton
						richColors
						theme="light"
						toastOptions={{
							classNames: {
								error: "bg-red-500 text-white", // Tailwind CSS classes for red background and white text
							},
						}}
					/>
				</body>
			</html>
		</ClerkProvider>
	);
}
