import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav/navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/footer/footer";
import { Toaster } from "@/components/ui/sonner";

const font = Montserrat({
	weight: "400",
	subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Medical Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={`${font.className} overflow-x-hidden antialiased max-w-7xl mx-auto px-2`}>
					<header className="mb-48">
						<NavBar />
					</header>
					{children}
					<Footer />
					<Toaster
						closeButton
						richColors
						theme="light"
						toastOptions={{
							classNames: {
								error: "bg-red-500 text-white", // Tailwind CSS classes for red background and white text
							},
						}}
					/>
				</body>
			</html>
		</ClerkProvider>
	);
}
